include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    prefer_int_literals: false
    constant_identifier_names: false
    sort_pub_dependencies: false
    one_member_abstracts: false
    lines_longer_than_80_chars: false
analyzer:

  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**.graphql.dart]
