include: package:lint/analysis_options_package.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    dead_code: warning
    deprecated_member_use_from_same_package: info
    deprecated_member_use: info
    missing_required_param: error
    missing_return: error
    todo: info
    unused_catch_clause: error
    unused_catch_stack: error
    unused_element: error
    unused_field: error
    unused_import: error
    unused_label: error
    unused_local_variable: error
    unused_result: error
    unused_shown_name: error

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"

  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 15
    halstead-volume: 150
    lines-of-code: 120
    maximum-nesting-level: 5
    number-of-methods: 12
    number-of-parameters: 6
    source-lines-of-code: 90
    weight-of-class: 0.33

  metrics-exclude:
    - test/**
  rules:
    # Common
    - avoid-collection-methods-with-unrelated-types
    - avoid-dynamic
    - avoid-global-state
    # TODO - remove this rule when we have a better way to handle the
    # - avoid-ignoring-return-values:
    #     exclude:
    #       - test/**
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - format-comment
    - member-ordering-extended:
        order:
          - named-constructors
          - factory-constructors
          - public-fields
          - private-fields
          - public-getters
          - private-getters
          - public-setters
          - private-setters
          - public-methods
          - private-methods
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-arguments:
        ignored-parameters:
          - height
          - width
          - backgroundColor
          - canvasColor
          - horizontal
          - vertical
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration
    - prefer-async-await
    - prefer-correct-identifier-length:
        exceptions: [ 'id', 'di', 'i' ]
        min-identifier-length: 2
        max-identifier-length: 90
    - prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions
    - prefer-correct-type-name:
        min-length: 2
        max-length: 90
    - prefer-first
    - prefer-immediate-return
    - prefer-last
    - prefer-match-file-name
    - prefer-trailing-comma

    # Flutter Specific
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file:
        ignore-private-widgets: true

  rules-exclude:
    - test/**

  anti-patterns:
    - long-method
    - long-parameter-list